### ISSUE TITLE
CUDA backend disabled when trying to import Sionna

### ISSUE THREAD

**Issue by taha-yassine** [NVlabs/sionna#111]
I'm trying to run the ray tracing tutorial notebook. After running the imports' cell I get the following error:
`jit_cuda_api_init(): could not find symbol "cuDevicePrimaryCtxRelease_v2" -- disabling CUDA backend!`

When I start a Python interactive session and try to import sionna I get more errors:
```bash
jit_cuda_api_init(): could not find symbol "cuDevicePrimaryCtxRelease_v2" -- disabling CUDA backend!
2023-03-29 17:18:42.865875: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:982] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-03-29 17:18:42.906978: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:982] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-03-29 17:18:42.907998: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:982] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
Traceback (most recent call last):
  File "/home/tyassine/.virtualenvs/sionna/lib/python3.8/site-packages/mitsuba/__init__.py", line 107, in __getattribute__
    _import('mitsuba.mitsuba_' + variant + '_ext'),
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 657, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1166, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: jit_init_thread_state(): the CUDA backend hasn't been initialized. Make sure to call jit_init(JitBackend::CUDA) to properly initialize this backend.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tyassine/.virtualenvs/sionna/lib/python3.8/site-packages/sionna/__init__.py", line 19, in <module>
    from . import rt
  File "/home/tyassine/.virtualenvs/sionna/lib/python3.8/site-packages/sionna/rt/__init__.py", line 23, in <module>
    mi.set_variant('cuda_ad_rgb')
  File "/home/tyassine/.virtualenvs/sionna/lib/python3.8/site-packages/mitsuba/__init__.py", line 317, in set_variant
    _import('mitsuba.ad.integrators')
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/tyassine/.virtualenvs/sionna/lib/python3.8/site-packages/mitsuba/python/ad/__init__.py", line 1, in <module>
    from .integrators import *
  File "/home/tyassine/.virtualenvs/sionna/lib/python3.8/site-packages/mitsuba/python/ad/integrators/__init__.py", line 25, in <module>
    importlib.import_module('mitsuba.ad.integrators.' + name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/tyassine/.virtualenvs/sionna/lib/python3.8/site-packages/mitsuba/python/ad/integrators/prb_basic.py", line 6, in <module>
    from .common import RBIntegrator
  File "/home/tyassine/.virtualenvs/sionna/lib/python3.8/site-packages/mitsuba/python/ad/integrators/common.py", line 8, in <module>
    class ADIntegrator(mi.CppADIntegrator):
  File "/home/tyassine/.virtualenvs/sionna/lib/python3.8/site-packages/mitsuba/__init__.py", line 253, in __getattribute__
    result = module.__getattribute__(key)
  File "/home/tyassine/.virtualenvs/sionna/lib/python3.8/site-packages/mitsuba/__init__.py", line 115, in __getattribute__
    raise AttributeError(e)
AttributeError: jit_init_thread_state(): the CUDA backend hasn't been initialized. Make sure to call jit_init(JitBackend::CUDA) to properly initialize this backend.
```

I'm using WSL2. I installed the NVIDIA drivers and toolkits following the [NVIDIA docs](https://docs.nvidia.com/cuda/wsl-user-guide/index.html#getting-started-with-cuda-on-wsl-2). I have the latest NVIDIA drivers installed on windows and have purposely intalled version 11.8 of the NVIDIA toolkit to comply with TF's requirements. I should mention that I encountered some problems related to some environment variables (`CUDNN_PATH` and `LD_LIBRARY_PATH`) not properly set that I manually managed to fix.

Any idea on what causes this?
Thanks in advance!

**Comment by taha-yassine** [comment]
After some investigation, it seems like the error stems from the fact that raytracing on GPU is not supported in WSL2 for now. https://github.com/mitsuba-renderer/drjit/issues/136
Maybe we can add a haeds-up to the README?

**Comment by gmarcusm** [comment]
Thanks for reporting it. We will add some clarifications for the next release.
