### ISSUE TITLE
Trouble using 'exhaustive' search in Sionna Ray-Tracing

### ISSUE THREAD

**Issue by TakashiDan0** [NVlabs/sionna#151]
Hi, i'm trying to usue sionna Ray Tracing, but i'm having trouble  using 'exhaustive' search. I'm having this error:

```
Traceback (most recent call last):
  File "/home/takashi/git/rwisimulation/sionna_sim.py", line 75, in run_simulation
    paths = scene.compute_paths(max_depth=6, method='exhaustive')
  File "/home/takashi/anaconda3/envs/latincom/lib/python3.8/site-packages/sionna/rt/scene.py", line 567, in compute_paths
    paths = self._solver(max_depth, sources, targets, method=method,
  File "/home/takashi/anaconda3/envs/latincom/lib/python3.8/site-packages/sionna/rt/solver.py", line 148, in __call__
    candidates = self._list_candidates_exhaustive(max_depth)
  File "/home/takashi/anaconda3/envs/latincom/lib/python3.8/site-packages/sionna/rt/solver.py", line 230, in _list_candidates_exhaustive
    all_candidates = tf.fill([num_samples, max_depth], -1)
  File "/home/takashi/anaconda3/envs/latincom/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/takashi/anaconda3/envs/latincom/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 103, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
ValueError: Can't convert Python sequence with out-of-range integer to Tensor.
```

The problem does not occur when using 'stochastic' search.

**Comment by faycalaa** [comment]
Hi,

Could you share a code snippet that reproduces this error?

**Comment by jhoydis** [comment]
Closed due to inactivity
