### ISSUE TITLE
Mapper class does not work with @tf.function

### ISSUE THREAD

**Issue by robinstart** [NVlabs/sionna#209]
Hi, I'm working with Sionna v0.15.1 and got some error in Mapper class.
```
ValueError: in user code:

    File "/Users/robin/coding/research2023/gfmmtc_rhnoma/code/simulator1.py", line 23, in main  *
        qam = Mapper("qam", N_bit)
    File "/Users/robin/coding/research2023/gfmmtc_rhnoma/venv/lib/python3.11/site-packages/sionna/mapping.py", line 511, in __init__  **
        self._binary_base = 2**tf.constant(

    ValueError: Expected values range(1, -1, -1) to be a dense tensor with shape [], but got shape [2].
```

The error arises in the last line of __init__ method.
[https://github.com/NVlabs/sionna/blob/f5ea373b948bfc367eaccdb8907889cfe62badd9/sionna/mapping.py#L512](url)

```python
def __init__(self,
             constellation_type=None,
             num_bits_per_symbol=None,
             constellation=None,
             return_indices=False,
             dtype=tf.complex64,
             **kwargs
            ):
    super().__init__(dtype=dtype, **kwargs)
    assert dtype in [tf.complex64, tf.complex128],\
        "dtype must be tf.complex64 or tf.complex128"

    # Create constellation object
    self._constellation = Constellation.create_or_check_constellation(
                                                    constellation_type,
                                                    num_bits_per_symbol,
                                                    constellation,
                                                    dtype=dtype)

    self._return_indices = return_indices

    self._binary_base = 2**tf.constant(
                    tf.range(self.constellation.num_bits_per_symbol-1,-1,-1))
```

It seems that tf.constant supports spreading the python "range" generator into an iterable in eager mode while **not in graph mode**. Below is a simple test snippet.

```python
import tensorflow as tf 

def test1():
    return tf.constant(range(1,5))

@tf.function
def test2():
    return tf.constant(range(1,5))

print(test1())
print(test2())
```

```
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
```
```
ValueError                                Traceback (most recent call last)
[/Users/robin/coding/research2023/gfmmtc_rhnoma/code/ex.py](https://file+.vscode-resource.vscode-cdn.net/Users/robin/coding/research2023/gfmmtc_rhnoma/code/ex.py) in line 12
      38     return tf.constant(range(1,5))
     40 print(test1())
---> 41 print(test2())

File [~/coding/research2023/gfmmtc_rhnoma/venv/lib/python3.11/site-packages/tensorflow/python/util/traceback_utils.py:153](https://file+.vscode-resource.vscode-cdn.net/Users/robin/coding/research2023/gfmmtc_rhnoma/~/coding/research2023/gfmmtc_rhnoma/venv/lib/python3.11/site-packages/tensorflow/python/util/traceback_utils.py:153), in filter_traceback..error_handler(*args, **kwargs)
    151 except Exception as e:
    152   filtered_tb = _process_traceback_frames(e.__traceback__)
--> 153   raise e.with_traceback(filtered_tb) from None
    154 finally:
    155   del filtered_tb

File [/var/folders/zr/p6362jb14r74xr6wrkvg2z0c0000gn/T/__autograph_generated_filehb0o6qye.py:12](https://file+.vscode-resource.vscode-cdn.net/var/folders/zr/p6362jb14r74xr6wrkvg2z0c0000gn/T/__autograph_generated_filehb0o6qye.py:12), in outer_factory..inner_factory..tf__test2()
     10 try:
     11     do_return = True
---> 12     retval_ = ag__.converted_call(ag__.ld(tf).constant, (ag__.converted_call(ag__.ld(range), (1, 5), None, fscope),), None, fscope)
     13 except:
     14     do_return = False

ValueError: in user code:

    File "", line 9, in test2  *
        return tf.constant(range(1,5))

    ValueError: Expected values range(1, 5) to be a dense tensor with shape [], but got shape [4].
```

Version informations:
Sionna: 0.15.1
tensorflow-macos: 2.13.0
macOS Montere: 12.6

**Comment by faycalaa** [comment]
Hi,

This error seems to arise due to the instantiation of the `Mapper` class in graph mode, which subsequently triggers its ``__init__()`` method to execute in the same mode.

You should instantiate `Mapper` outside of graph mode. Once instantiated, you can call it in graph mode.
