### ISSUE TITLE
problem with DRJIT_LIBLLVM_PATH

### ISSUE THREAD

**Issue by gnarwhal97** [NVlabs/sionna#223]
Hello! When trying to execute the code:

```
scene = load_scene(sionna.rt.scene.munich)
```

I get an error:

```
>>> scene = load_scene(sionna.rt.scene.munich)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/vladislavprosvirov/sionna_test/venv/lib/python3.11/site-packages/sionna/rt/scene.py", line 1498, in load_scene
    return Scene(filename, dtype=dtype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vladislavprosvirov/sionna_test/venv/lib/python3.11/site-packages/sionna/rt/scene.py", line 131, in __init__
    self._scene = mi.load_file(env_filename)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: [xml.cpp:215] Error while loading "/Users/vladislavprosvirov/sionna_test/venv/lib/python3.11/site-packages/sionna/rt/scenes/munich/munich.xml" (at line 11, col 3): jit_init_thread_state(): the LLVM backend is inactive because the LLVM shared library ("libLLVM.dylib") could not be found! Set the DRJIT_LIBLLVM_PATH environment variable to specify its path..
```

I have installed llvm via brew.

**Comment by merlinND** [comment]
Hello @gnarwhal97,

Have you tried setting the `DRJIT_LIBLLVM_PATH` environment variable to specify the path to `libLLVM.dylib` ?

**Comment by merlinND** [comment]
@yhaddint has kindly shared his experience in the following comment, which should be applicable to your setup as well: https://github.com/NVlabs/sionna/discussions/160#discussioncomment-7170294

Could you please give it a try?

**Comment by gnarwhal97** [comment]
The problem was solved, thank you very much!
