### ISSUE TITLE
“INVALID_ARGUMENT:  Input is not invertible” when using the function zero_forcing_precoder

### ISSUE THREAD

**Issue by SedrickWang** [NVlabs/sionna#226]
The sim_ber function works fine when I use the ZF-precoder to simulate MIMO downlink communication, but it gives an error when the SNR is high (see the following information). The function zero_forcing_precoder seems to be using the inverse of the matrix instead of the pseudo-inverse. Does that make sense?

```bash
EbNo [dB] |        BER |       BLER |  bit errors |    num bits | block errors |  num blocks | runtime [s] |    status
---------------------------------------------------------------------------------------------------------------------------------------
      0.0 | 2.3218e-01 | 9.8340e-01 |      439848 |     1894400 |         1007 |        1024 |         8.6 |reached target block errors
      1.0 | 1.9685e-01 | 9.1276e-01 |      559383 |     2841600 |         1402 |        1536 |         0.5 |reached target block errors
      2.0 | 1.5363e-01 | 7.6758e-01 |      436565 |     2841600 |         1179 |        1536 |         0.5 |reached target block errors
      3.0 | 1.2047e-01 | 5.9912e-01 |      456445 |     3788800 |         1227 |        2048 |         0.6 |reached target block errors
      4.0 | 9.5697e-02 | 4.7070e-01 |      453223 |     4736000 |         1205 |        2560 |         0.8 |reached target block errors
      5.0 | 8.0634e-02 | 3.9687e-01 |      381884 |     4736000 |         1016 |        2560 |         0.8 |reached target block errors
      6.0 | 6.0006e-02 | 2.9018e-01 |      397867 |     6630400 |         1040 |        3584 |         1.1 |reached target block errors
      7.0 | 4.6800e-02 | 2.2569e-01 |      398961 |     8524800 |         1040 |        4608 |         1.4 |reached target block errors
      8.0 | 3.1169e-02 | 1.5400e-01 |      383801 |    12313600 |         1025 |        6656 |         2.0 |reached target block errors
      9.0 | 2.9173e-02 | 1.3802e-01 |      414493 |    14208000 |         1060 |        7680 |         2.3 |reached target block errors
     10.0 | 2.3605e-02 | 1.1068e-01 |      402458 |    17049600 |         1020 |        9216 |         2.8 |reached target block errors
     11.0 | 1.7203e-02 | 8.4066e-02 |      391069 |    22732800 |         1033 |       12288 |         3.8 |reached target block errors
     12.0 | 1.2964e-02 | 6.5209e-02 |      380652 |    29363200 |         1035 |       15872 |         4.9 |reached target block errors
     13.0 | 1.1230e-02 | 5.3790e-02 |      393563 |    35046400 |         1019 |       18944 |         5.8 |reached target block errors
     14.0 | 8.8061e-03 | 4.2502e-02 |      383691 |    43571200 |         1001 |       23552 |         7.2 |reached target block errors
     15.0 | 6.5010e-03 | 3.2275e-02 |      375620 |    57779200 |         1008 |       31232 |         9.5 |reached target block errors
     16.0 | 5.8054e-03 | 2.7619e-02 |      390417 |    67251200 |         1004 |       36352 |        11.1 |reached target block errors
     17.0 | 4.5401e-03 | 2.1293e-02 |      395635 |    87142400 |         1003 |       47104 |        14.4 |reached target block errors
     18.0 | 3.8743e-03 | 1.8242e-02 |      366974 |    94720000 |          934 |       51200 |        15.7 |reached max iter       
Traceback (most recent call last):2 |       70648 |    24627200 |          197 |       13312 |         4.1 |iter: 25/100
  File "/root/Project2/StagedSparseTraining/Evaluation/MainEstimator/eval.py", line 61, in <module>
    ber, bler = eval_main_estimator(model=model,
  File "/root/Project2/StagedSparseTraining/Utils/functions.py", line 385, in eval_main_estimator
    ber, bler = sionna.utils.sim_ber(EvalMainEstimator(model=model, config=config),
  File "/usr/local/lib/python3.8/dist-packages/sionna/utils/misc.py", line 633, in sim_ber
    outputs = mc_fun(batch_size=batch_size, ebno_db=ebno_dbs[i])
  File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/execute.py", line 52, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Exception encountered when calling layer 'EvalMainEstimator' (type EvalMainEstimator).

Graph execution error:

Detected at node 'zf_precoder/MatrixInverse' defined at (most recent call last):
    File "/root/Project2/StagedSparseTraining/Evaluation/MainEstimator/eval.py", line 61, in <module>
      ber, bler = eval_main_estimator(model=model,
    File "/root/Project2/StagedSparseTraining/Utils/functions.py", line 385, in eval_main_estimator
      ber, bler = sionna.utils.sim_ber(EvalMainEstimator(model=model, config=config),
    File "/usr/local/lib/python3.8/dist-packages/sionna/utils/misc.py", line 633, in sim_ber
      outputs = mc_fun(batch_size=batch_size, ebno_db=ebno_dbs[i])
    File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 561, in __call__
      return super().__call__(*args, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/keras/engine/base_layer.py", line 1132, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 96, in error_handler
      return fn(*args, **kwargs)
    File "/root/Project2/StagedSparseTraining/Utils/functions.py", line 328, in call
      batch_x_rg, batch_g = self._config._zf_precoder([batch_x_rg, batch_h_freq])
    File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/keras/engine/base_layer.py", line 1132, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 96, in error_handler
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/sionna/ofdm/precoding.py", line 169, in call
      x_precoded, g = zero_forcing_precoder(x_precoded,
    File "/usr/local/lib/python3.8/dist-packages/sionna/mimo/precoding.py", line 77, in zero_forcing_precoder
      g = tf.matmul(h, h, adjoint_b=True)
    File "/usr/local/lib/python3.8/dist-packages/sionna/utils/tensors.py", line 282, in matrix_inv
      if tensor.dtype in [tf.complex64, tf.complex128] \
    File "/usr/local/lib/python3.8/dist-packages/sionna/utils/tensors.py", line 295, in matrix_inv
      return tf.matmul(u*s, u, adjoint_b=True)
Node: 'zf_precoder/MatrixInverse'
```

**Comment by jhoydis** [comment]
Closed due to inactivity.
