### ISSUE TITLE
Sionna doesn't work with GPU through WSL2

### ISSUE THREAD

**Issue by paolofiore90** [NVlabs/sionna#562]
I'm trying to run Sionna with my GPU on Windows 11. Since, as it is stated, Tensorflow doesn't have any GPU support since 2.10, I figured to use WSL2 to host my python interpreter. Tensorflow by itself detects the GPU in WSL2 when imported, but Sionna doesn't.

These are the hardware/software specifications in my experiment:
Windows 11
WSL2
Nvidia Gforce GTX 1650 with Max-Q Design
Nvidia driver 560.81
CUDA 11.8
CUDNN 8.6
Python 3.8
Tensorflow 2.13
Sionna 0.17

With just Tensorflow, when I try to check the GPUs accessible with 
print(tf.config.list_physical_devices('GPU')), this error message appears:

```
I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
```

But if I simply import Sionna, this happens:

```
jit_cuda_api_init(): could not find symbol "cuDevicePrimaryCtxRelease_v2" -- disabling CUDA backend!
2024-09-04 12:03:16.714464: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.

Traceback (most recent call last):
  File "/home/user/.virtualenvs/myproject/lib/python3.8/site-packages/mitsuba/__init__.py", line 107, in __getattribute__
    _import('mitsuba.mitsuba_' + variant + '_ext'),
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 657, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1166, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: jit_init_thread_state(): the CUDA backend hasn't been initialized. Make sure to call jit_init(JitBackend::CUDA) to properly initialize this backend.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.virtualenvs/myproject/lib/python3.8/site-packages/sionna/__init__.py", line 19, in <module>
    from . import rt
  File "/home/user/.virtualenvs/myproject/lib/python3.8/site-packages/sionna/rt/__init__.py", line 22, in <module>
    mi.set_variant('cuda_ad_rgb')
  File "/home/user/.virtualenvs/myproject/lib/python3.8/site-packages/mitsuba/__init__.py", line 317, in set_variant
    _import('mitsuba.ad.integrators')
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/user/.virtualenvs/myproject/lib/python3.8/site-packages/mitsuba/python/ad/__init__.py", line 2, in <module>
    from .integrators import *
  File "/home/user/.virtualenvs/myproject/lib/python3.8/site-packages/mitsuba/python/ad/integrators/__init__.py", line 25, in <module>
    importlib.import_module('mitsuba.ad.integrators.' + name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/user/.virtualenvs/myproject/lib/python3.8/site-packages/mitsuba/python/ad/integrators/prb.py", line 6, in <module>
    from .common import RBIntegrator, mis_weight
  File "/home/user/.virtualenvs/myproject/lib/python3.8/site-packages/mitsuba/python/ad/integrators/common.py", line 8, in <module>
    class ADIntegrator(mi.CppADIntegrator):
  File "/home/user/.virtualenvs/myproject/lib/python3.8/site-packages/mitsuba/__init__.py", line 253, in __getattribute__
    result = module.__getattribute__(key)
  File "/home/user/.virtualenvs/myproject/lib/python3.8/site-packages/mitsuba/__init__.py", line 115, in __getattribute__
    raise AttributeError(e)
AttributeError: jit_init_thread_state(): the CUDA backend hasn't been initialized. Make sure to call jit_init(JitBackend::CUDA) to properly initialize this backend.
```

the first message (jit_cuda_api_init(): could not find symbol "cuDevicePrimaryCtxRelease_v2" -- disabling CUDA backend!), seems the most promising to find the origin of the problem, but I don't know if I'm missing something or if there is some compatibility issue.

**Comment by merlinND** [comment]
Hello @paolofiore90,

This has been discussed several times before, OptiX is not officially available through WSL on Windows and therefore Sionna ray tracing cannot be used.
Please search existing issues and discussions.

If you do not intend to use any of Sionna's ray tracing-related features, I think it should be possible to skip the `mitsuba` import and use the rest of the library (although I haven't tested this myself).
