### ISSUE TITLE
Mac M1 Could not find compiler for platform METAL

### ISSUE THREAD

**Issue by ocatak** [NVlabs/sionna#78]
**Describe the bug**
I am trying to execute "Part 2: Differentiable Communication Systems" on my macos m1 based python environment.

**To Reproduce**
When I execute the following part, I get an error
```
ber_plots.simulate(model,
                  ebno_dbs=np.linspace(EBN0_DB_MIN, EBN0_DB_MAX, 20),
                  batch_size=BATCH_SIZE,
                  num_target_block_errors=100, # simulate until 100 block errors occured
                  legend="Untrained model",
                  soft_estimates=True,
                  max_mc_iter=100, # run 100 Monte-Carlo simulations (each with batch_size samples)
                  show_fig=True);
```

Error:
```

tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at xla_ops.cc:296 : UNIMPLEMENTED: Could not find compiler for platform METAL: NOT_FOUND: could not find registered compiler for platform METAL -- check target linkage
Traceback (most recent call last):

  File "/Users/ozgur/miniforge3/lib/python3.9/site-packages/spyder_kernels/py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "/Users/ozgur/Dropbox/MyPublications/6G/sionna_ex/basic_tutorial_02.py", line 252, in <module>
    ber_plots.simulate(model,

  File "/Users/ozgur/miniforge3/lib/python3.9/site-packages/sionna/utils/plotting.py", line 411, in simulate
    ber, bler = sim_ber(mc_fun,

  File "/Users/ozgur/miniforge3/lib/python3.9/site-packages/sionna/utils/misc.py", line 633, in sim_ber
    outputs = mc_fun(batch_size=batch_size, ebno_db=ebno_dbs[i])

  File "/Users/ozgur/miniforge3/lib/python3.9/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None

  File "/Users/ozgur/miniforge3/lib/python3.9/site-packages/tensorflow/python/eager/execute.py", line 54, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,

UnimplementedError: Could not find compiler for platform METAL: NOT_FOUND: could not find registered compiler for platform METAL -- check target linkage [Op:__inference___call___123156]
```

**Comment by jhoydis** [comment]
Hi,

I believe that this is an issue related to TensorFlow and not Sionna. Have you tried running the code without Metal?

**Comment by ocatak** [comment]
Hi,

I guess for Mac M1 users, we need to disable jist_compile (jit_compile=False). It works now, Of course it is slow now.
